name: Build d3d9.dll for both 32-bit and 64-bit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Download Detours source code
      - name: Download Detours
        run: |
          curl -L -o detours.zip https://github.com/microsoft/Detours/archive/refs/heads/master.zip
          unzip detours.zip -d detours
          
      # Optional: Build Detours library (if you need a static lib)
      - name: Build Detours Library
        shell: cmd
        run: |
          REM Set paths
          set DETOURS_DIR=%GITHUB_WORKSPACE%\detours\Detours-master
          
          REM Find Visual Studio installation
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VSINSTALLDIR=%%i
          
          REM Build for x86
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x86
          msbuild "%DETOURS_DIR%\detours.sln" /p:Configuration=Release /p:Platform=Win32
          
          REM Build for x64
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x64
          msbuild "%DETOURS_DIR%\detours.sln" /p:Configuration=Release /p:Platform=x64
          
      # Step 2: Build 32-bit DLL
      - name: Build 32-bit DLL
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          DETOURS_INCLUDE: ${{ github.workspace }}\detours\Detours-master\include
          DETOURS_LIB_X86: ${{ github.workspace }}\detours\Detours-master\lib.X86
        run: |
          REM Find latest VS installation path
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VSINSTALLDIR=%%i
          
          REM Call vcvarsall for x86
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x86
          
          REM Build for x86 with Detours include and lib paths
          msbuild d3d9_proxy.vcxproj /p:Configuration=Release /p:Platform=x86 /m \
            /p:AdditionalIncludeDirectories="%DETOURS_INCLUDE%" \
            /p:AdditionalLibraryDirectories="%DETOURS_LIB_X86%"
          
          REM Create artifacts directory if not exists
          mkdir "%GITHUB_WORKSPACE%\artifacts\x86" 2>NUL
          REM Copy the built DLL to artifacts folder
          copy /Y "bin\d3d9.dll" "%GITHUB_WORKSPACE%\artifacts\x86\"
      
      # Step 3: Build 64-bit DLL
      - name: Build 64-bit DLL
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          DETOURS_INCLUDE: ${{ github.workspace }}\detours\Detours-master\include
          DETOURS_LIB_X64: ${{ github.workspace }}\detours\Detours-master\lib.X64
        run: |
          REM Find latest VS installation path
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VSINSTALLDIR=%%i
          
          REM Call vcvarsall for x64
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x64
          
          REM Build for x64 with Detours include and lib paths
          msbuild d3d9_proxy.vcxproj /p:Configuration=Release /p:Platform=x64 /m \
            /p:AdditionalIncludeDirectories="%DETOURS_INCLUDE%" \
            /p:AdditionalLibraryDirectories="%DETOURS_LIB_X64%"
          
          REM Create artifacts directory if not exists
          mkdir "%GITHUB_WORKSPACE%\artifacts\x64" 2>NUL
          REM Copy the built DLL to artifacts folder
          copy /Y "bin\x64\d3d9.dll" "%GITHUB_WORKSPACE%\artifacts\x64\"

      # Step 4: Upload artifacts
      - name: Upload 32-bit DLL
        uses: actions/upload-artifact@v4
        with:
          name: d3d9-dll-32bit
          path: artifacts\x86

      - name: Upload 64-bit DLL
        uses: actions/upload-artifact@v4
        with:
          name: d3d9-dll-64bit
          path: artifacts\x64
