name: Build d3d9.dll 32-bit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with MSBuild
        shell: cmd
        run: |
          REM Find latest VS installation path
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VSINSTALLDIR=%%i
          REM Call vcvarsall for x86
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x86
          REM Build Release x86
          msbuild d3d9_proxy.vcxproj /p:Configuration=Release /p:Platform=x86 /m

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: d3d9-dll-32bit
          path: bin\d3d9.dll
