name: Build d3d9 32-bit DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSVC environment for 32-bit
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86

    - name: Compile d3d9_proxy.cpp to 32-bit DLL named d3d9.dll
      run: |
        cl.exe /LD /EHsc d3d9_proxy.cpp /Fe:d3d9.dll

    - name: Upload DLL as artifact
      uses: actions/upload-artifact@v3
      with:
        name: d3d9-dll-32bit
        path: d3d9.dll
