name: Build d3d9 32-bit DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build d3d9.dll 32-bit using MSVC (cmd shell)
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86
        cl.exe /LD /EHsc d3d9_proxy.cpp /Fe:d3d9.dll

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: d3d9-dll-32bit
        path: d3d9.dll
