name: Build d3d9 32-bit DLL with MSBuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build DLL with MSBuild
        run: msbuild d3d9_proxy.vcxproj /p:Configuration=Release /p:Platform=x86

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: d3d9-dll-32bit
          path: bin\d3d9.dll
