name: Build D3D9 Proxy DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build 32-bit DLL
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Add MSBuild to PATH
      run: |
        echo "Adding MSBuild to PATH"
        echo "$env:MSBUILD_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Create Visual Studio project file
      run: |
        $projectContent = @'
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{$(New-Guid)}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>d3d9proxy</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="Shared">
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <LinkIncremental>false</LinkIncremental>
    <OutDir>bin\</OutDir>
    <IntDir>obj\</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <Optimization>MaxSpeed</Optimization>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_USRDLL;D3D9PROXY_EXPORTS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <SDLCheck>true</SDLCheck>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>false</GenerateDebugInformation>
      <ModuleDefinitionFile>d3d9.def</ModuleDefinitionFile>
      <ImportLibrary>$(OutDir)d3d9.lib</ImportLibrary>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="d3d9_proxy.cpp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="d3d9.def" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>
'@
        Set-Content -Path "d3d9proxy.vcxproj" -Value $projectContent

        $defContent = @'
LIBRARY d3d9.dll
EXPORTS
    D3DPERF_BeginEvent=Real_D3DPERF_BeginEvent @1
    D3DPERF_EndEvent=Real_D3DPERF_EndEvent @2
    D3DPERF_GetStatus=Real_D3DPERF_GetStatus @3
    D3DPERF_QueryRepeatFrame=Real_D3DPERF_QueryRepeatFrame @4
    D3DPERF_SetMarker=Real_D3DPERF_SetMarker @5
    D3DPERF_SetOptions=Real_D3DPERF_SetOptions @6
    D3DPERF_SetRegion=Real_D3DPERF_SetRegion @7
    DebugSetLevel=Real_DebugSetLevel @8
    DebugSetMute=Real_DebugSetMute @9
    Direct3DCreate9=Real_Direct3DCreate9 @10
    Direct3DCreate9Ex=Real_Direct3DCreate9Ex @11
'@
        Set-Content -Path "d3d9.def" -Value $defContent

    - name: Build DLL
      run: |
        msbuild d3d9proxy.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: d3d9-proxy-dll
        path: bin/d3d9.dll
